// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ChinChunPetShop.Models.Entity;

namespace ChinChunPetShop.Models.ViewModel
{
    public partial class CTNhanVien:NhanVien
    {
        public List<string> VaiTroNhanVien { get; set; }

    }
}
