// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class CTDT
{
    public string MaDT { get; set; }

    public string MaSP { get; set; }

    public int SoLuong { get; set; }

    public string TinhTrangSP { get; set; }

    public string GhiChu { get; set; }

    public virtual DoiTraHang MaDTNavigation { get; set; }

    public virtual SanPham MaSPNavigation { get; set; }
}