// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class CTGiaoDich
{
    public string MaSP { get; set; }

    public string MaSK { get; set; }

    public int SoLuong { get; set; }

    public decimal DonGia { get; set; }

    public virtual SoKho MaSKNavigation { get; set; }

    public virtual SanPham MaSPNavigation { get; set; }
}