// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class CTKM
{
    public string MaKM { get; set; }

    public string TenCTKM { get; set; }

    public int? PhanTramGiam { get; set; }

    public DateTime NgayBatDau { get; set; }

    public DateTime NgayKetThuc { get; set; }

    public string MoTa { get; set; }

    public virtual ICollection<SPKM> SPKMs { get; set; } = new List<SPKM>();
}