// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class DoiTraHang
{
    public string MaDT { get; set; }

    public string MaDH { get; set; }

    public DateTime NgayDT { get; set; }

    public string LiDoDT { get; set; }

    public bool TrangThai { get; set; }

    public DateTime? NgayXuLy { get; set; }

    public string GhiChu { get; set; }

    public string MaNV { get; set; }

    public virtual ICollection<CTDT> CTDTs { get; set; } = new List<CTDT>();

    public virtual DonHang MaDHNavigation { get; set; }

    public virtual NhanVien MaNVNavigation { get; set; }
}