// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class DonHang
{
    public string MaDH { get; set; }

    public string MaNV { get; set; }

    public string MaKH { get; set; }

    public string MaTTDH { get; set; }

    public string MaPTTT { get; set; }

    public string TenNguoiNhan { get; set; }

    public string DiaChiGiaoHang { get; set; }

    public string SDTNguoiNhan { get; set; }

    public decimal PhiGiaoHang { get; set; }

    public DateTime NgayMuaHang { get; set; }

    public DateTime? NgayNhanHang { get; set; }

    public string GhiChu { get; set; }

    public bool LoaiDH { get; set; }

    public bool ThanhToan { get; set; }

    public virtual ICollection<CTDH> CTDHs { get; set; } = new List<CTDH>();

    public virtual ICollection<DoiTraHang> DoiTraHangs { get; set; } = new List<DoiTraHang>();

    public virtual KhachHang MaKHNavigation { get; set; }

    public virtual NhanVien MaNVNavigation { get; set; }

    public virtual PTTT MaPTTTNavigation { get; set; }

    public virtual TrangThaiDH MaTTDHNavigation { get; set; }
}