// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class GioHang
{
    public string MaGH { get; set; }

    public string MaSP { get; set; }

    public string MaKH { get; set; }

    public int SoLuong { get; set; }

    public decimal DonGia { get; set; }

    public virtual KhachHang MaKHNavigation { get; set; }

    public virtual SanPham MaSPNavigation { get; set; }
}