// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class KhachHang
{
    public string MaKH { get; set; }

    public string HoTen { get; set; }

    public string SDT { get; set; }

    public string Email { get; set; }

    public DateOnly? NgaySinh { get; set; }

    public bool? GioiTinh { get; set; }

    public string DiaChi { get; set; }

    public int? Diem { get; set; }

    public DateTime? NgayTaoTK { get; set; }

    public string MatKhau { get; set; }

    public bool TrangThai { get; set; }

    public bool? XacThucEmail { get; set; }

    public string MaXacThuc { get; set; }

    public DateTime? ThoiHanMXT { get; set; }

    public string HinhAnh { get; set; }

    public virtual ICollection<DonHang> DonHangs { get; set; } = new List<DonHang>();

    public virtual ICollection<GioHang> GioHangs { get; set; } = new List<GioHang>();
}