// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class MocTangQua
{
    public string MaMTQ { get; set; }

    public int? SoDiem { get; set; }

    public decimal? GiaTri { get; set; }
}