// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class NhanVien
{
    public string MaNV { get; set; }

    public string HoNV { get; set; }

    public string TenNV { get; set; }

    public string Email { get; set; }

    public string SDT { get; set; }

    public DateOnly? NgaySinh { get; set; }

    public bool? GioiTinh { get; set; }

    public string DiaChi { get; set; }

    public decimal Luong { get; set; }

    public string MatKhau { get; set; }

    public DateOnly? NgayVaoLam { get; set; }

    public bool? XacThucEmail { get; set; }

    public string MaXacThuc { get; set; }

    public DateTime? ThoiHanMXT { get; set; }

    public string HinhAnh { get; set; }

    public virtual ICollection<DoiTraHang> DoiTraHangs { get; set; } = new List<DoiTraHang>();

    public virtual ICollection<DonHang> DonHangs { get; set; } = new List<DonHang>();

    public virtual ICollection<PhanQuyen> PhanQuyens { get; set; } = new List<PhanQuyen>();

    public virtual ICollection<SoKho> SoKhos { get; set; } = new List<SoKho>();
}