// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class PhanQuyen
{
    public string MaVT { get; set; }

    public string MaNV { get; set; }

    public string GhiChu { get; set; }

    public virtual NhanVien MaNVNavigation { get; set; }

    public virtual VaiTro MaVTNavigation { get; set; }
}