// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class PhiVanChuyen
{
    public int KhoiLuongMin { get; set; }

    public int? KhoiLuongMax { get; set; }

    public decimal ChiPhi { get; set; }

    public decimal? ChiPhiThem { get; set; }
}