// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class SanPham
{
    public string MaSP { get; set; }

    public string TenSP { get; set; }

    public string MaSKU { get; set; }

    public string MaLoaiSP { get; set; }

    public string MaNhanHieu { get; set; }

    public int? KhoiLuong { get; set; }

    public string MaVach { get; set; }

    public string DonViTinh { get; set; }

    public string MoTa { get; set; }

    public decimal GiaBanLe { get; set; }

    public decimal? GiaBanSi { get; set; }

    public decimal GiaNhap { get; set; }

    public string HinhAnh { get; set; }

    public string GioiThieu { get; set; }

    public virtual ICollection<CTDH> CTDHs { get; set; } = new List<CTDH>();

    public virtual ICollection<CTDT> CTDTs { get; set; } = new List<CTDT>();

    public virtual ICollection<CTGiaoDich> CTGiaoDiches { get; set; } = new List<CTGiaoDich>();

    public virtual ICollection<GioHang> GioHangs { get; set; } = new List<GioHang>();

    public virtual LoaiSanPham MaLoaiSPNavigation { get; set; }

    public virtual NhanHieu MaNhanHieuNavigation { get; set; }

    public virtual ICollection<SPKM> SPKMs { get; set; } = new List<SPKM>();

    public virtual ICollection<TonKho> TonKhos { get; set; } = new List<TonKho>();
}