// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class SoKho
{
    public string MaSK { get; set; }

    public bool LoaiGiaoDich { get; set; }

    public DateTime NgayGiaoDich { get; set; }

    public string MaNV { get; set; }

    public string LyDoNhapXuat { get; set; }

    public string GhiChu { get; set; }

    public virtual ICollection<CTGiaoDich> CTGiaoDiches { get; set; } = new List<CTGiaoDich>();

    public virtual NhanVien MaNVNavigation { get; set; }
}