// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class SPKM
{
    public string MaKM { get; set; }

    public string MaSP { get; set; }

    public string Ghichu { get; set; }

    public virtual CTKM MaKMNavigation { get; set; }

    public virtual SanPham MaSPNavigation { get; set; }
}