// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class ThamSo
{
    public string MaTS { get; set; }

    public int TonKhoCanhBao { get; set; }

    public int TonKhoToiThieu { get; set; }

    public int TonKhoToiDa { get; set; }

    public decimal GiaTriGhiDiem { get; set; }

    public int SoNgayDoiTra { get; set; }

    public int SLMuaSiToiThieu { get; set; }

    public int ThoiGianTuDongHuyDon { get; set; }

    public int ThoiGianTraHang { get; set; }

    public DateTime NgayCapNhat { get; set; }
}