// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinChunPetShop.Models.Entity;

public partial class TonKho
{
    public string MaSP { get; set; }

    public string MaKho { get; set; }

    public int SLTrongKho { get; set; }

    public int SLCoTheBan { get; set; }

    public int SLDaBan { get; set; }

    public virtual KhoHang MaKhoNavigation { get; set; }

    public virtual SanPham MaSPNavigation { get; set; }
}